[project]
name = "portas-abertas-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "loguru>=0.7.3",
    "pyjwt[crypto]>=2.13.0",
    "tzdata>=2026.3",
    "uvicorn>=0.52.4",
]

[tool.ruff]
src = ["src"]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]


[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ruff>=0.16.4",
    "ty>=0.0.74",
]
